---
- name: Cobbler Install Playbook
  hosts: cblr_server
  become: true
  tasks:
  - include: Cent7.yml
    when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

  - fail:
      msg: "{{ ansible_distribution }} {{ ansible_distribution_major_version }} not supported"
    when: ansible_distribution != "CentOS" and ansible_distribution_major_version != "7"
